## 복습

불량조건 
det|A| = 0 은 아니지만 거의 0에 가까움

|A||A^-1| ~ 0 인 경우

In [119]:
import numpy as np

A = np.array([[2,1],
             [2,1.002]])

B = np.array([0,1])

print(np.linalg.solve(A,B))

detA = np.linalg.det(A)
print(detA)

[-250.  500.]
0.004000000000000005


In [120]:
A1 = np.linalg.inv(A)
print(np.dot(A,A1))

[[1. 0.]
 [0. 1.]]


In [121]:
def Gauss(a,b):
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
            
    for k in range(n-1,-1,-1):
        b[k]  = (b[k] - np.dot((a[k,k+1:n]),b[k+1:n])) / a[k,k]
    return b

In [122]:
A = np.array([[6,-4,1],
              [-4,6,-4],
              [1,-4,6]])
B = np.array([[-14,22],
              [36,-18],
              [6,7]])
print(B)

[[-14  22]
 [ 36 -18]
 [  6   7]]


In [123]:
lam1 = A[1,0] / A[0,0]
lam2 = A[2,0] / A[0,0]
# A[1,0] = A[1,0] - A[0,0] * lam1
# A[1,1] = A[1,1] - A[0,1] * lam1
# A[1,2] = A[1,2] - A[0,2] * lam1

A[1,:] = A[1,:] - A[0,:] * lam1 
A[2,:] = A[2,:] - A[0,:] * lam2

lam3 = A[2,1] / A[1,1]
A[2,:] = A[2,:] - A[1,:] * lam3

print(A)

[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]


In [ ]:
lamb1 = B[1,0] / B[0,0]
lamb2 = B[2,0] / B[0,0]

B[1,:] = B[1,:] - B[0,:] * lamb1
B[2,:] = B[2,:] - B[0,:] * lamb2


print(B)

In [71]:
B = B.T
lamb1 = B[1,0] / B[0,0]
#lamb2 = B[2,0] / B[0,0]

B[1,:] = B[1,:] - B[0,:] * lamb1
#B[2,:] = B[2,:] - B[0,:] * lamb2


print(B)

[[-14  36   6]
 [  0  38  16]]


In [79]:
lamb1 =  B[0,1] / B[0,0]

B[:,1] = B[:,1] - B[:,0] * lamb1

print(B)

[[-14   0]
 [ 36  38]
 [  6  16]]


In [77]:
a = A[0:3,0:2]
b = A[0:3,2:3]
b1 = b.T
Gauss(a,b1)

array([[0, 0, 1]])

In [2]:
import numpy as np
A = np.array([[6,-4,1],
              [-4,6,-4],
              [1,-4,6]])
B = np.array([[-14,22],
              [36,-18],
              [6,7]])


C = np.hstack([A,B])
#C0 = C.copy()


#C1 = C0[0,:]
#C2 = C0[1,:]

#C[0,:] = C2
#C[1,:] = C1

print(C)

print('                             ')
lam1 = C[1,0] / C[0,0]
lam2 = C[2,0] / C[0,0]
#C[1,0] = C[1,0] - C[0,0] * lam1
#C[1,1] = C[1,1] - C[0,1] * lam1
#C[2,] = C[1,2] - C[0,2] * lam2

C[1,:] = C[1,:] - C[0,:] * lam1 
C[2,:] = C[2,:] - C[0,:] * lam2

lam3 = C[2,1] / C[1,1]
C[2,:] = C[2,:] - C[1,:] * lam3

#lam4 = C[2,2] / C[1,2]
#C[2,:] = C[2,:] - C[1,:] * lam4


x3 = C[2,2]




print(C)

[[  6  -4   1 -14  22]
 [ -4   6  -4  36 -18]
 [  1  -4   6   6   7]]
                             
[[  6  -4   1 -14  22]
 [  0   3  -3  26  -3]
 [  0   0   2  34   0]]


In [128]:
print(A)
print(A*A)
print(np.dot(A,A))
print(A@A)

[[ 6 -4  1]
 [-4  6 -4]
 [ 1 -4  6]]
[[36 16  1]
 [16 36 16]
 [ 1 16 36]]
[[ 53 -52  28]
 [-52  68 -52]
 [ 28 -52  53]]
[[ 53 -52  28]
 [-52  68 -52]
 [ 28 -52  53]]


In [ ]:
"""
a = 1
b = 2


temp = a
b = a
b = temp

a, b = b, a
"""

In [10]:
C = A.copy()
print(C)

[[ 6 -4  1]
 [-4  6 -4]
 [ 1 -4  6]]


In [4]:
C[0]

array([ 6, -4,  1])

In [5]:
C[1]

array([-4,  6, -4])

In [6]:
C[[0,2]]

array([[ 6, -4,  1],
       [ 1, -4,  6]])

In [9]:
C[[0,2]] = C[[2,0]]  #Row swap

#C[:,[0,2]] = C[:,[2,0]] # Colunm swap
print(C)

[[ 1 -4  6]
 [-4  6 -4]
 [ 6 -4  1]]


A = LU
A@X = B
L@U@A = B

L@Y = B
Y= U@X