## 1번

In [1]:
import numpy as np
A = np.eye(1000, k=0, dtype = int)
B = np.eye(1000, k=1, dtype = int)
C = np.eye(1000, k=-1, dtype = int)
print(2*A + 3*B + C)



[[2 3 0 ... 0 0 0]
 [1 2 3 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 ...
 [0 0 0 ... 2 3 0]
 [0 0 0 ... 1 2 3]
 [0 0 0 ... 0 1 2]]


## 2번

In [2]:
import numpy as np
# x + 2*y = 10
# x - 3*y = 5

A = np.array([[1,2],
               [1,-3]])
b = np.array([10,5])

ans = np.linalg.solve(A,b)
print('x=' , ans[0])
print('y=' , ans[1])

x= 8.0
y= 1.0


## 3번

In [2]:
import numpy as np
# 5 – s – 2p – d = 0
# 7 – 2s + p + 3d = 0
# 2s – 4 – f – 2g = 0
# 2p – 2 – 2f + g = 0
# 2d – f + 3g = 0
A = np.array([[-1,-2,-1,0,0],
              [-2,1,3,0,0],
              [2,0,0,-1,-2],
              [0,2,0,-2,1],
              [0,0,2,-1,3]])
B = np.array([-5,-7,4,2,0])
c = np.linalg.solve(A,B)
s = (c[0])
p = (c[1])
d = (c[2])
f = (c[3])
g = (c[4])
print(c)
print(5 - s - 2 * p - d)
print(7 - 2*s + p + 3*d)
print(2*s - 4 - f - 2*g)
print(2*p - 2 - 2*f + g)
print(2*d - f + 3*g)


[ 3.06666667  1.33333333 -0.73333333  0.69333333  0.72      ]
0.0
4.440892098500626e-16
-4.440892098500626e-16
2.220446049250313e-16
0.0


## 4번

In [5]:
import numpy as np

theta = 20 * (np.pi) / 180
## theta = np.deg2rad(20)
A = np.array([[np.cos(theta),-np.sin(theta)],
               [np.sin(theta),np.cos(theta)]])
b = np.array([1,0])
#print(A)
print(np.dot(A,b))
A@b

[0.93969262 0.34202014]


array([0.93969262, 0.34202014])

## 5번

In [8]:
import numpy as np

A = np.array([[2.46,0.00,0.00],
             [-1.23,2.14,0.00],
             [0.00,0.00,10.00]])
dotV1 = np.array([1,0,0])
dotV2 = np.array([0,1,0])
dotV3 = np.array([0,0,1])

v1 = np.linalg.solve(A,dotV1)
v2 = np.linalg.solve(A,dotV2)
v3 = np.linalg.solve(A,dotV3)

print('v1=',v1)
print('v2=',v2)
print('v3=',v3)

b = np.eye(3)
v = np.linalg.solve(A,b)
v.T

v1= [0.40650407 0.23364486 0.        ]
v2= [0.         0.46728972 0.        ]
v3= [0.  0.  0.1]


array([[0.40650407, 0.23364486, 0.        ],
       [0.        , 0.46728972, 0.        ],
       [0.        , 0.        , 0.1       ]])