In [9]:
import numpy as np

A =np.random.rand(3,4)
b = A[:,3]

print(A)

[[0.60090386 0.57566048 0.62900099 0.91501522]
 [0.36346673 0.45528552 0.88328294 0.21423544]
 [0.32031953 0.17826784 0.14630612 0.97559371]]


In [14]:
a = A[0:3,0:3]
n = a.shape[0]
n = len(a)
print(a)

[[0.60090386 0.57566048 0.62900099]
 [0.36346673 0.45528552 0.88328294]
 [0.32031953 0.17826784 0.14630612]]


In [13]:
aa = a.copy()
print(aa)

[[ 1  2  3]
 [ 2 -5 -8]
 [ 3 -2  8]]


### ----------------------------

In [92]:
import numpy as np
a = np.array([[1.0,1.0,1.0],
              [2.0,1.0,2.0],
             [3.0,1.0,4.0]])
n = a.shape[0]
print(n)

3


In [2]:
import numpy as np

A =np.random.rand(3,4)
b = A[:,3]
a = A[0:3,0:3]
aa = a.copy()
b = A[:,3]
bb = b.copy()

x = np.zeros(len(b))
n = len(a)

In [127]:
for k in range(0,n-1):
    for i in range(k+1,n):
        if a[i,k] != 0.0:
            #print('loop',i,k)
            
            lam = a[i,k] / a[k,k]
            #a[i,k] = 0.0
            a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
            
            b[i] = b[i] - lam*b[k]
for k in range(n-1,-1,-1):
    x[k] = (b[k] - (np.dot(a[k,k+1:n], x[k+1:n]))) / a[k,k]  #j = k+!, ... , n
    

In [128]:
print(a)
print(aa)
print(np.linalg.solve(aa,bb))
print(x)

[[ 7.46057516e-01  1.69686796e-01  7.67829670e-02]
 [-1.11022302e-16  9.44857999e-02  8.62317161e-01]
 [ 1.11022302e-16  0.00000000e+00 -2.75366311e+00]]
[[0.74605752 0.1696868  0.07678297]
 [0.8180201  0.2805401  0.94650639]
 [0.85555383 0.59329637 0.9731406 ]]
[-0.34625737  1.42046114  0.27113634]
[-0.34625737  1.42046114  0.27113634]


####  =====================

In [6]:
import time
import numpy as np
time_start = time.time()

A = np.zeros((4000,4000))

for i in range(4000):
    for j in range(4000):
        A[i,j] = A[i,j] + 1
time_finish = time.time()

print(time_finish - time_start)

10.829761028289795


In [26]:
import time
import numpy as np
time_start = time.time()

A = np.zeros((4000,4000))
A = A + np.ones((4000,4000))
time_finish = time.time()
print(time_finish - time_start)

0.13799810409545898


In [3]:
def Gauss(a,b):
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
            
    for k in range(n-1,-1,-1):
        b[k]  = (b[k] - np.dot((a[k,k+1:n]),b[k+1:n])) / a[k,k]
    return b

Gauss(A,b)

array([ 0.22274753, -0.79992403,  1.05144592])

# ---- upper

In [1]:
import numpy as np

A =np.random.rand(3,4)
b = A[:,3]
a = A[0:3,0:3]
aa = a.copy()
b = A[:,3]
bb = b.copy()

x = np.zeros(len(b))
n = len(a)
print(a)

[[0.29170703 0.50295924 0.75742684]
 [0.96251305 0.4751928  0.62053353]
 [0.61109439 0.09030754 0.28064275]]


In [2]:
for k in range(n-1,0,-1):
    for i in range(k-1,-1,-1):
        if a[i,k] != 0.0:
           
            lam = a[i,k] / a[k,k]
            a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
            
            b[i] = b[i] - lam*b[k]
for k in range(0,n):
    if a[k,k] != 0:
        x[k] = (b[k] - (np.dot(a[k,k+1:n], x[k+1:n]))) / a[k,k]  #j = k+!, ... , n


In [3]:
print(a)
print(x)
print(np.linalg.solve(aa,bb))

[[0.29170703 0.         0.        ]
 [0.96251305 0.4751928  0.        ]
 [0.61109439 0.09030754 0.28064275]]
[-2.39429249 -1.24334796  2.23758415]
[ 0.7741766  -1.05228459  0.89044176]


In [4]:
print(np.linalg.solve(aa,bb))

[ 0.7741766  -1.05228459  0.89044176]


In [177]:
b1 = [1,2,3]
b2 = [5,4,3]

bmat = np.array([[1,2],
               [2,3],
               [3,4]])

bmat1= np.array([b1,b2])
bmat2 = np.vstack((b1,b2))
c = np.shape(b2)
print(c[0])


def Gauss(a,b):
    B = np.array([])
    
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
            
    for k in range(n-1,-1,-1):
        b[k]  = (b[k] - np.dot((a[k,k+1:n]),b[k+1:n])) / a[k,k]
    return b


3


In [29]:
def Gauss(a,b):
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
            
    for k in range(n-1,-1,-1):
        b[k]  = (b[k] - np.dot((a[k,k+1:n]),b[k+1:n])) / a[k,k]
    return b

Gauss(A,b)

array([-0.50425948, -0.728104  ,  1.02778661])