In [5]:
from ch2 import *
from scipy.linalg import *
import numpy as np

a = np.array([[3.0 , -1.0, 4.0],
             [-2.0,0.0,5.0],
             [7.0, 2.0,-2.0]])


b = np.array([[6.0,3.0,7.0],
              [-4.0,2,0,-5.0]])

ModuleNotFoundError: No module named 'ch2'

In [73]:
lu, piv = lu_factor(a)
lu_solve((lu,piv),b.T)

ValueError: incompatible dimensions.

### ----------------------------------------------------

In [21]:
import numpy as np

amat = np.array([[3.0 , -1.0, 4.0],
             [-2.0,0.0,5.0],
             [7.0, 2.0,-2.0]])

b = np.array([6.0,3.0,7.0])

a = amat.copy()

np.linalg.solve(amat,b)

array([1., 1., 1.])

In [22]:
# LU 분해
a = amat.copy()

lam1 = a[1,0] / a[0,0]
a[1] = a[1] - lam1 * a[0]


lam2 = a[2,0] / a[0,0]
a[2] = a[2] - lam2 * a[0]


lam3 = a[2,1] / a[1,1]
a[2] = a[2] - lam3 * a[1]
print(a)

U = a.copy()
print('U',U)
L = np.zeros([3,3])

#L = L + np.diag([1,1,1])

L = L + np.eye(3)


L[1,0] = lam1
L[2,0] = lam2
L[2,1] = lam3

print(lam1,lam2,lam3)
print('L',L)

[[ 3.         -1.          4.        ]
 [ 0.         -0.66666667  7.66666667]
 [ 0.          0.         38.5       ]]
U [[ 3.         -1.          4.        ]
 [ 0.         -0.66666667  7.66666667]
 [ 0.          0.         38.5       ]]
-0.6666666666666666 2.3333333333333335 -6.500000000000001
L [[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 2.33333333 -6.5         1.        ]]


In [27]:
n = len(b)

# 전진대입
y = np.zeros(n)

y[0] = b[0]

for k in range(1,n):
    y[k] = b[k] - np.dot(L[k,0:k],y[0:k])


print('y',y)
# 후진대입
x = np.zeros(n)

#y1 = y.copy()

for k in range(n-1,-1,-1):
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n])) / U[k,k]


print(x)

y [ 6.   7.  38.5]
[1. 1. 1.]


### -------------------------------------------

In [57]:
"""
Ax = b

LUx = b

Ly = b

Ux = y

"""

'\nAx = b\n\nLUx = b\n\nLy = b\n\nUx = y\n\n'

In [35]:
import numpy as np

a = np.array([[1,4,1],
              [1,6,-1],
              [2,-1,2]])

b = np.array([7,13,5])

np.linalg.solve(a,b)

array([ 5.,  1., -2.])

In [36]:
amat = a.copy()
lam1 = a[1,0] / a[0,0]
a[1] = a[1] - lam1 * a[0]


lam2 = a[2,0] / a[0,0]
a[2] = a[2] - lam2 * a[0]


lam3 = a[2,1] / a[1,1]
a[2] = a[2] - lam3 * a[1]


U = a.copy()
print('U',U)
L = np.zeros([3,3])
L = L + np.eye(3)


L[1,0] = lam1
L[2,0] = lam2
L[2,1] = lam3

print(lam1,lam2,lam3)
print('L',L)

print(L@U)

U [[ 1  4  1]
 [ 0  2 -2]
 [ 0  0 -9]]
1.0 2.0 -4.5
L [[ 1.   0.   0. ]
 [ 1.   1.   0. ]
 [ 2.  -4.5  1. ]]
[[ 1.  4.  1.]
 [ 1.  6. -1.]
 [ 2. -1.  2.]]


In [37]:
n = len(b)

# 전진대입
y = np.zeros(n)

y[0] = b[0]

for k in range(1,n):
    y[k] = b[k] - np.dot(L[k,0:k],y[0:k])    


# 후진대입
x = np.zeros(n)
for k in range(n-1,-1,-1):
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n])) / U[k,k]

print('x =', x)

x = [ 5.  1. -2.]


### -------------------------------------