# 과제2 2017550012 배준영

## 1번

In [36]:
import numpy as np

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]])

B = np.array([3,13,4])

Acopy = A.copy()
Bcopy = B.copy()
# 소거

lam1 = A[1,0] / A[0,0]
lam2 = A[2,0] / A[0,0]


A[1,:] = A[1,:] - A[0,:] * lam1 
B[1] = B[1] - B[0] * lam1
A[2,:] = A[2,:] - A[0,:] * lam2
B[2] = B[2] - B[0] * lam2

lam3 = A[2,1] / A[1,1]
A[2,:] = A[2,:] - A[1,:] * lam3
B[2] = B[2] - B[1] * lam3



print("상삼각행렬"); print(A); print(B)

상삼각행렬
[[1 2 4]
 [0 2 2]
 [0 0 3]]
[ 3  4 -6]


In [37]:
# 후진 대입
n = len(B)
x = np.zeros(n)

for k in range(n-1,-1,-1):
    x[k] = (B[k] - np.dot(A[k,k+1:n],x[k+1:n])) / A[k,k]

print("My answer\n",x)
print("linalg.solve\n", np.linalg.solve(Acopy,Bcopy))



My answer
 [ 3.  4. -2.]
linalg.solve
 [ 3.  4. -2.]


In [4]:
# 한번에 소거
import numpy as np

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]])

B = np.array([[3],
              [13],
              [4]])


Acopy = A.copy()
Bcopy = B.copy()

C = np.hstack([A,B])

lam1 = C[1,0] / C[0,0]
lam2 = C[2,0] / C[0,0]


C[1,:] = C[1,:] - C[0,:] * lam1 
C[2,:] = C[2,:] - C[0,:] * lam2

lam3 = C[2,1] / C[1,1]
C[2,:] = C[2,:] - C[1,:] * lam3

n = len(B)
x = np.zeros(n)
bc = C[0:3,3]


for k in range(n-1,-1,-1):
    x[k] = (bc[k] - np.dot(C[k,k+1:n],x[k+1:n])) / C[k,k]


print("My answer\n",x)

My answer
 [ 3.  4. -2.]


## 2번

In [5]:
import numpy as np

A = np.array([[0, 0, 2, 1, 2],
              [0, 1, 0, 2, -1],
              [1, 2, 0, -2, 0],
              [0, 0, 0, -1, 1],
              [0, 1, -1, 1, -1]])

B = np.array([1, 1, -4, -2, -1])

Acopy = A.copy()
Bcopy = B.copy()

# 정렬

A[[0,2]] = A[[2,0]]
B[[0,2]] = B[[2,0]]

A[[1,4]] = A[[4,1]]
B[[1,4]] = B[[4,1]]

A[[2,4]] = A[[4,2]]
B[[2,4]] = B[[4,2]]

A[[3,4]] = A[[4,3]]
B[[3,4]] = B[[4,3]]

print(A)
print(B)

[[ 1  2  0 -2  0]
 [ 0  1 -1  1 -1]
 [ 0  1  0  2 -1]
 [ 0  0  2  1  2]
 [ 0  0  0 -1  1]]
[-4 -1  1  1 -2]


In [6]:
# 소거
lam1 = A[2,1] / A[1,1]
A[2,:] = A[2,:] - A[1,:] * lam1
B[2] = B[2] - B[1] * lam1

lam2 = A[3,2] / A[2,2]
A[3,:] = A[3,:] - A[2,:] * lam2
B[3] = B[3] - B[2] * lam2

lam3 = A[4,3] / A[3,3]
A[4,:] = A[4,:] - A[3,:] * lam3
B[4] = B[4] - B[3] * lam3
print("A\n",A)
print("B\n",B)

A
 [[ 1  2  0 -2  0]
 [ 0  1 -1  1 -1]
 [ 0  0  1  1  0]
 [ 0  0  0 -1  2]
 [ 0  0  0  0 -1]]
B
 [-4 -1  2 -3  1]


In [41]:
# 후진대입
n = len(B)
x = np.zeros(n)

for k in range(n-1,-1,-1):
    x[k] = (B[k] - np.dot(A[k,k+1:n],x[k+1:n])) / A[k,k]


print("My answer\n",x)
print("linalg.solve\n",np.linalg.solve(Acopy,Bcopy))

My answer
 [ 2. -2.  1.  1. -1.]
linalg.solve
 [ 2. -2.  1.  1. -1.]


## 3번

#### 하삼각행렬 / 전진대입

In [2]:
# 하삼각행렬
def gauss_down(a,b):
    n = len(b)
    x = np.zeros(n)
    for k in range(n-1,0,-1): 
        for i in range(k-1,-1,-1):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                
                a[i,0:k+1] = a[i,0:k+1] - lam * a[k,0:k+1]
                b[i] = b[i] - lam * b[k]
    for k in range(0,n):
            x[k] = ( b[k] - np.dot(a[k,0:k],x[0:k]) ) / a[k,k]
        
    return x

In [3]:
import numpy as np

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]], dtype = 'f8')

B = np.array([3,13,4], dtype = 'f8')
Acopy = A.copy()
Bcopy = B.copy()

print("전진대입\n",gauss_down(A,B))

print("linalg.solve\n",np.linalg.solve(Acopy,Bcopy))

전진대입
 [ 3.  4. -2.]
linalg.solve
 [ 3.  4. -2.]


#### 상삼각행렬 / 후진대입

In [4]:
# 상삼각행렬
def gauss_up(a,b):
    n = len(b)
    x = np.zeros(n)
    for k in range(0,n):
        for i in range(k+1,n): 
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k] 
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n] 
                b[i] = b[i] - lam*b[k]

    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n])) / a[k,k]
    return x

In [5]:
import numpy as np

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]], dtype ='f8')

B = np.array([3,13,4],dtype ='f8')

print("후진대입\n",gauss_up(A,B))

후진대입
 [ 3.  4. -2.]


## 4번

In [22]:
import numpy as np


def LUdecomp_solve(a,b):
    n = len(a)
    x = np.zeros(n)
    y = np.zeros(n)
    L = np.eye(n) # doolittle
    U = a.copy()
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k] / a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam *a[k,k+1:n]
              
                lam = U[i,k] / U[k,k]
                U[i,k+1:n] = U[i,k+1:n] - lam *U[k,k+1:n]
                
                a[i,k] = lam
                L[i,k] = lam
                U[i,k] = 0
    print('L\n',L)
    print('U\n',U)
    y[0] = b[0]
    for k in range(1,n):
        y[k] = b[k] - np.dot(a[k,0:k],y[0:k])
    print(y)
    for k in range(n-1,-1,-1):
        x[k] = (y[k] - np.dot(a[k,k+1:n],x[k+1:n]) ) / a[k,k]
        
    return x

In [23]:

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]],dtype='f8')

B = np.array([3,13,4],dtype='f8')

Ac = A.copy()
Bc = B.copy()


print("LU decomposition and solve\n",LUdecomp_solve(A,B))
print("linalg.solve\n",np.linalg.solve(Ac,Bc))

L
 [[1. 0. 0.]
 [3. 1. 0.]
 [2. 1. 1.]]
U
 [[1. 2. 4.]
 [0. 2. 2.]
 [0. 0. 3.]]
[ 3.  4. -6.]
[ 0.  0. -2.]
[ 0.  4. -2.]
[ 3.  4. -2.]
LU decomposition and solve
 [ 3.  4. -2.]
linalg.solve
 [ 3.  4. -2.]


## 5번

In [9]:
import numpy as np

m1 = 10; m2 = 4; m3 = 5; m4 = 6 # kg
mu1 = 0.25; mu2 = 0.3; mu3 = 0.2 
g = 10 # m/s^2
theta = 40 * np.pi / 180 # rad

# X = ( T1, T2, T3, a)

A = np.array([[1, 0, 0, m1],
              [-1, 1, 0, m2],
              [0, -1, 1, m3],
              [0, 0, -1, m4]])

B = np.array([(m1 * g * (np.sin(theta) - mu1 * np.cos(theta)) ),
             (m2 * g * (np.sin(theta) - mu2 * np.cos(theta)) ),
             (m3 * g * (np.sin(theta) - mu3 * np.cos(theta)) ),
              (-m4 * g)])

ac = A.copy()
bc = B.copy()


C = np.linalg.solve(A,B)
T1 = C[0]; T2 = C[1]; T3 = C[2]; a = C[3]



print('LU분해\n',LUdecomp_solve(ac,bc))
print('linalg.solve\n',C)
print('\nT1 = ',T1,'\nT2 =',T2,'\nT3 = ', T3,'\na = ', a)

L
 [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
U
 [[ 1  0  0 10]
 [ 0  1  0 14]
 [ 0  0  1 19]
 [ 0  0  0 25]]
LU분해
 [34.67742709 47.01630903 66.27013368  1.04502228]
linalg.solve
 [34.67742709 47.01630903 66.27013368  1.04502228]

T1 =  34.67742708513928 
T2 = 47.01630903295704 
T3 =  66.27013368332412 
a =  1.04502228055402


### 마찰 x

In [10]:
import numpy as np

m1 = 10; m2 = 4; m3 = 5; m4 = 6 # kg
g = 10 # m/s^2
theta = 40 * np.pi / 180 # rad

# X = ( T1, T2, T3, a)

A = np.array([[1, 0, 0, m1],
              [-1, 1, 0, m2],
              [0, -1, 1, m3],
              [0, 0, -1, m4]])

B = np.array([(m1 * g * (np.sin(theta)) ),
             (m2 * g * (np.sin(theta)) ),
             (m3 * g * (np.sin(theta)) ),
              (-m4 * g)])


ac = A.copy()
bc = B.copy()


C = np.linalg.solve(A,B)
T1 = C[0]; T2 = C[1]; T3 = C[2]; a = C[3]



print('LU분해\n',LUdecomp_solve(A,B))



print('linalg.solve\n',np.linalg.solve(ac,bc))
print('\nT1 = ',T1,'\nT2 =',T2,'\nT3 = ', T3,'\na = ', a)

L
 [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
U
 [[ 1  0  0 10]
 [ 0  1  0 14]
 [ 0  0  1 19]
 [ 0  0  0 25]]
LU분해
 [39.42690263 55.19766369 74.911115    2.48518583]
linalg.solve
 [39.42690263 55.19766369 74.911115    2.48518583]

T1 =  39.42690263247694 
T2 = 55.197663685467724 
T3 =  74.9111150017062 
a =  2.4851858336176984
